### ISSUE TITLE
Dow - Senior Developer (.NET) - 上海

### ISSUE THREAD

**Issue by tonyqus** [dotnet-cn/jobs#16]
Senior Developer will help in continuing to bring the DxC vision to life. As a Senior developer, you will be responsible for working with a scrum team through design, development, and implementation of workable digital solutions that meet business and functional stakeholder requirements, while exploring and prototyping the latest technologies. You will be a proponent and practitioner of Dow's Agile Scrum methodology and strategy.  You will be a mentor to less experienced developers on your direct scrum team, work with other senior developers within the DMC, and collaborate with all developers within the DxC network. Additionally, you will help deliver demonstrations of technologies through showcases and participate in design thinking workshops, along with event storming sessions with stakeholders.

**Job Responsibilities / Duties:**

•       Ability to understand the importance of good software design and development principles to ensure that the DxC is able to produce software of the highest quality, in the most efficient timeline, and will maintain these ideals throughout future projects.

•       Work with Lead and Senior Developers to define the scope and solution architecture of products.

•       Lead the development of cloud-first Web/Mobile/AI/ML solutions.

•       Mentor and coach junior developers on your scrum team

•       Understand complex data sources and integrations and develop/implement necessary data flows.

•       Implement top-tier security and data protection.

•       Build reusable code and libraries for future use and sharing across Dow.

•       Contribute to the best practices for the Digital Center Network and Dow.

•       Gather requirements to write acceptance criteria and user stories with the customers / product owners collaboratively as part of a team.

•       Work closely with other Dow teams (ex: DSA, ISS, ITS) in order to turn your solution into reality.

•       Help shape and guide the adoption of cloud technologies that integrate or interface with legacy systems.

•       Ensure that cross-team collaboration is happening within and outside the project team through explicit activities like knowledge sharing, architectural and design reviews and code reuse.

**Required Qualifications:**

•       A minimum of a Bachelor's degree with a major in Computer Science, Information Systems, Engineering, or related technical field.

•       A minimum of 5 years of software solution development experience.

•       General knowledge of Information technology work process, methodologies, and tools.

•       Modern software engineering skills, including experience with object-oriented programming and material design patterns.

**Preferred Qualifications:**

•       Recent experience designing and deploying in Microsoft Azure’s Environment.

•       Proficient knowledge in front-end and/or back-end development.

•       Demonstrated knowledge and experience in Agile software development methodologies and work processes, especially Scrum.

•       Participated in application development process from requirements through implementation.

•       Excellent Leadership & Communication Skills.

•       Design Thinking and Human Centered Design experience.

•       Familiarity with Code and Frameworks from recent developments: ASP.NET, C#, Angular, HTML, JavaScript, JQuery.

•       Familiarity with Common Azure Cloud Services: Azure Apps, Key Vault, Azure AD, App Insights, SQL, Functions, Containers, Data Factory, Azure ML, API Manager and more.

**Dow Offers:** 

A robust total rewards program, including: competitive base pay, variable pay that rewards individual, team, and Company performance, and comprehensive benefits
On-going learning opportunities within a diverse, inclusive and rewarding work environment 
Career experiences that can span different Dow businesses and functions with opportunities for personal and professional growth 
The chance to work within a global company and interact with colleagues from around the world 
Opportunities that spark your imagination and ignite your passion to help others 

有兴趣的发简历到tony.qu@nissl.com.cn

**Comment by TTonlyV5** [comment]
您好，我已收到您的邮件，会尽快处理。

**Comment by tonyqus** [comment]
没看懂
