### ISSUE TITLE
网易游戏已经不使用dotnet了

### ISSUE THREAD

**Issue by alvin-su** [dotnet-cn/jobs#19]
用友和网易游戏 应该不使用.net 了

**Comment by tonyqus** [comment]
啊？unity他们不用吗？那他们用什么？

**Comment by alvin-su** [comment]
前端还是unity，后端服务不是dotnet了
> 啊？unity他们不用吗？那他们用什么？

**Comment by tonyqus** [comment]
那unity也是用C#写的呀，那还是.net呀，哈哈哈。他们从微软买了300million美金 support service呢。
