### ISSUE TITLE
广州埃维诺技术咨询上海分公司（埃森哲&微软子公司）校招

### ISSUE THREAD

**Issue by tonyqus** [dotnet-cn/jobs#22]
**关于埃维诺 Avanade** 

埃维诺是一家由 Microsoft Corporation 和 Accenture LLP 共同投资的合资企业。我们的解决方案依托久经验证的工具、方法和实践，建立在独一无二的深入见解、创新能力和技术知识组合之上。埃维诺愿景是成为数字化创新领导者，借助人才和 Microsoft 生态系统的力量为我们的客户及他们的客户实现卓越成果的同时，创造卓越的体验。 

我们帮助数以千计的企业成功实现了数字化转型。其中包括为他们的客户和员工打造良好的用户体验。我们帮助客户降低了企业成本，提高了工作效率，实现了团队协作，增加了灵活度，最终实现企业成果。 

**职位说明**
 
• 了解业务的需求，最终帮助客户实现可落地的数字化转型

• 依据业务需求，快速适应不同的项目角色（包括但不限于设计、开发、项目管理等）
 
• 通过日常应用技术的学习，完成文档设计、编写、单元测试等工作，

• 可独立研究工作，最终成为可以为客户提供可落地的解决方案的高级软件工程师

 **职位要求** 

• 2022年应届本科及硕士毕业生
 
• 计算机科学, 软件工程, 信息技术/系统, 电子信息, 通信工程等IT相关专业；或想从事软件行业的理工科专业

• 熟悉JAVA/.NET, SQL, NodeJS中的一种或多种，对.NET开发体系感兴趣优先

• 大学英语四级（CET-4）及以上

• 良好的逻辑能力及快速学习能力

• 有志于在软件开发领域发展自己的职业生涯

简历投递到tonyqus@gmail.com

**Comment by XgHao** [comment]
可惜只要应届的😢

**Comment by tonyqus** [comment]
@XgHao 你看哪种机会？社招也有职位

**Comment by XgHao** [comment]
> @XgHao 你看哪种机会？社招也有职位
麻烦问下 杭州有.NET岗位吗 目前做的后端🏃‍♂️

**Comment by tonyqus** [comment]
你把简历发我下, 我记得我群里有杭州的大佬招人，tonyqus@gmail.com
