### ISSUE TITLE
凌像科技 - 杭州 .NET 桌面客户端开发工程师

### ISSUE THREAD

**Issue by dongmingsun** [dotnet-cn/jobs#26]
# 职位描述

## 岗位职责

负责一款激光加工设备的客户端软件开发，具体包含：

1. 参与项目的需求分析
2. 参与各功能模块的设计和开发，与视觉算法工程师、运动控制工程师配合，完成产品的架构、编码和测试
3. 根据项目情况，短期性出差解决客户问题

## 任职要求

**教育背景：** 本科及以上学历，计算机及相关专业

**语言要求：** 能熟练运用英语查阅资料

**知识技能：**

1. 熟悉 C# 语言，具备 C/S 架构开发经验，熟练掌握异步、多线程等技术
2. 熟悉 .NET Framework ，2 年及以上 WinForms 或 WPF 开发经验
3. 熟悉数据库的编程及应用（例如 SQLite 、MySQL ），能熟练编写 SQL 语句
4. 熟练掌握 git ，具备良好版本管理习惯
5. 具备良好的沟通能力和编程习惯，善于编写技术文档

## 加分项

1. 具有 C++/CLI 、C++ STL 、Python 等语言的使用经验
2. 具有 MES 系统或 OPC UA 开发经验
3. 具有单元测试框架使用经验

# 薪资福利及工作制度

**薪资：** 16-18K ，根据绩效发放双月奖+年终奖，实际年收入为 14~16 个月（正常情况下为15个月）

**工作时间：** 弹性工作制，上班时间为 9:00-10:00 ，下班时间为 18:00-19:00 ；双休，节假日不加班

**员工激励：** 在薪资的基础上，公司还设立了丰厚的技术贡献奖金、专利奖金、项目奖金等，鼓励员工进行技术创新和知识沉淀

**员工福利：** 节日津贴、每年体检、生日礼包、团建聚餐旅游、零食、下午茶、加班打车报销，每月额外发放餐补、通信费、交通补贴

**股权激励：** 对于优秀员工，公司有员工持股计划，一人一议

# 关于我们

[凌像科技](https://surimage.cn/)是一家专注于先进制造的初创公司，团队由硕博士为主、年轻充满活力，**目前已获得某头部机构的天使轮投资**。期待优秀的你与公司一起成长，共同打造中国智造高端品牌。

📍工作地点：杭州市

📧简历投递邮箱（标题注明 dotnet-cn ）： [contact@surimage.cn](mailto:contact@surimage.cn)

**Comment by tonyqus** [comment]
不如直接来群里问问有没有愿意去，加群通道: https://github.com/dotnet-cn/jobs/issues/13

**Comment by dongmingsun** [comment]
好的哦
对了，接受PR有什么要求吗？ @tonyqus

**Comment by tonyqus** [comment]
把公司信息写清楚就行，创业公司都能加，请注意公司行业分类

**Comment by TTonlyV5** [comment]
您好，我已收到您的邮件，会尽快处理。
