### ISSUE TITLE
.NET高级开发工程师 - 聚水潭

### ISSUE THREAD

**Issue by tonyqus** [dotnet-cn/jobs#7]
薪资范围: 15-30K
职位地点：上海
公司地址：上海市闵行区新虹街道申长路990弄虹桥汇T4号楼6楼
此为内推职位

一、岗位职责：
1、按时按要求完成分配的开发任务，编写设计文档;
2、解决日常工作中的技术难题;
3、配合其他项目小组协查程序问题;
4、其它上级临时交代的工作事项。
二、任职要求：
1、本科及以上学历，计算机相关专业，.NET开发相关岗位5年以上从业经验;
2、有.NETcore开发经验者优先；熟悉Abp框架者优先；
3、熟悉常用设计模式，对DDD、OO、IOC、AOP等有一定认识；
4、熟悉c#开发，熟悉asp.net开发，熟悉html，jquery，熟悉sqlserver相关开发;
5、有ERP或者电商行业经验者优先;
6、对工作认真负责，有敬业精神，能承受一定的工作压力。
 

简历发送至：feiyi1@jushuitan.com，注明岗位

**Comment by liguobao** [comment]
积水潭这公司之前看到过，只是不太确定他们在搞撒。

**Comment by tonyqus** [comment]
我跟他们也不算太熟

**Comment by tonyqus** [comment]
@liguobao 来群里
![image](https://user-images.githubusercontent.com/772561/129285834-1bedcf48-a39a-4fc1-9eba-f031ad198ba9.png)
