### ISSUE TITLE
群二维码过期

### ISSUE THREAD

**Issue by seleningchan** [dotnet-cn/jobs#9]
群二维码过期，无法加入群

**Comment by tonyqus** [comment]
![image](https://user-images.githubusercontent.com/772561/132161559-7680d7db-2183-4f3a-9a72-27e296af0f9b.png)

**Comment by tonyqus** [comment]
已更新

**Comment by tenove** [comment]
群二维码过期，无法加入群

**Comment by tonyqus** [comment]
![image](https://user-images.githubusercontent.com/772561/135701086-a7a842a8-70ae-4a23-954d-b58278279d4c.png)
